export const TODAY_ISO = "2026-08-31T12:00:00.000Z";

export const FIRST_NAMES = [
  "James",
  "Maria",
  "Robert",
  "Linda",
  "Michael",
  "Patricia",
  "David",
  "Jennifer",
  "William",
  "Elizabeth",
  "Carlos",
  "Sofia",
  "Daniel",
  "Amanda",
  "Kevin",
  "Michelle",
  "Brian",
  "Nicole",
  "Steven",
  "Angela",
  "Marcus",
  "Rachel",
  "Anthony",
  "Laura",
  "Jason",
  "Megan",
  "Eric",
  "Stephanie",
  "Justin",
  "Kimberly",
  "Andre",
  "Diana",
  "Victor",
  "Christina",
  "Derek",
  "Samantha",
  "Tyler",
  "Rebecca",
  "Nathan",
  "Vanessa",
  "Omar",
  "Priya",
  "Wei",
  "Fatima",
  "Luis",
  "Grace",
  "Hassan",
  "Olivia",
  "Ivan",
  "Natasha",
];
export const LAST_NAMES = [
  "Johnson",
  "Garcia",
  "Smith",
  "Williams",
  "Brown",
  "Davis",
  "Miller",
  "Wilson",
  "Moore",
  "Taylor",
  "Anderson",
  "Thomas",
  "Jackson",
  "White",
  "Harris",
  "Martin",
  "Thompson",
  "Young",
  "Robinson",
  "Walker",
  "Hernandez",
  "King",
  "Wright",
  "Lopez",
  "Hill",
  "Scott",
  "Green",
  "Adams",
  "Baker",
  "Nelson",
  "Rivera",
  "Campbell",
  "Mitchell",
  "Carter",
  "Roberts",
  "Gomez",
  "Phillips",
  "Evans",
  "Turner",
  "Torres",
  "Parker",
  "Collins",
  "Edwards",
  "Stewart",
  "Flores",
  "Morris",
  "Murphy",
  "Cook",
  "Rogers",
  "Reed",
];

export const CITIES: { city: string; state: string }[] = [
  { city: "Atlanta", state: "GA" },
  { city: "Dallas", state: "TX" },
  { city: "Chicago", state: "IL" },
  { city: "Denver", state: "CO" },
  { city: "Phoenix", state: "AZ" },
  { city: "Seattle", state: "WA" },
  { city: "Portland", state: "OR" },
  { city: "Memphis", state: "TN" },
  { city: "Columbus", state: "OH" },
  { city: "Charlotte", state: "NC" },
  { city: "Indianapolis", state: "IN" },
  { city: "Kansas City", state: "MO" },
  { city: "Nashville", state: "TN" },
  { city: "Salt Lake City", state: "UT" },
  { city: "Sacramento", state: "CA" },
  { city: "Austin", state: "TX" },
  { city: "Orlando", state: "FL" },
  { city: "Pittsburgh", state: "PA" },
  { city: "Cincinnati", state: "OH" },
  { city: "Raleigh", state: "NC" },
  { city: "Louisville", state: "KY" },
  { city: "Oklahoma City", state: "OK" },
  { city: "Richmond", state: "VA" },
  { city: "Boise", state: "ID" },
  { city: "Tucson", state: "AZ" },
  { city: "Reno", state: "NV" },
  { city: "Omaha", state: "NE" },
  { city: "Baton Rouge", state: "LA" },
  { city: "Albuquerque", state: "NM" },
  { city: "Spokane", state: "WA" },
];

export const VEHICLE_MAKES_MODELS: { make: string; models: string[]; type: string }[] = [
  { make: "Freightliner", models: ["Cascadia", "M2 106", "Columbia"], type: "Semi Truck" },
  { make: "Peterbilt", models: ["579", "389", "567"], type: "Semi Truck" },
  { make: "Kenworth", models: ["T680", "W900", "T880"], type: "Semi Truck" },
  { make: "Volvo", models: ["VNL 860", "VNR 300", "VHD"], type: "Semi Truck" },
  { make: "International", models: ["LT Series", "MV Series"], type: "Box Truck" },
  { make: "Ford", models: ["Transit 350", "F-650", "E-Transit"], type: "Van" },
  { make: "Mercedes-Benz", models: ["Sprinter 2500", "Sprinter 3500"], type: "Van" },
  { make: "Isuzu", models: ["NPR-HD", "NQR"], type: "Box Truck" },
  { make: "Hino", models: ["268", "195"], type: "Box Truck" },
  { make: "Chevrolet", models: ["Express 3500", "Silverado 3500HD"], type: "Van" },
  { make: "Ram", models: ["ProMaster 3500", "5500 Chassis"], type: "Van" },
  { make: "Mack", models: ["Anthem", "Pinnacle"], type: "Semi Truck" },
];

export const DEPOTS = [
  { id: "loc-main", name: "Main Depot", city: "Dallas", state: "TX", type: "Depot" },
  { id: "loc-north", name: "North Depot", city: "Chicago", state: "IL", type: "Depot" },
  { id: "loc-south", name: "South Depot", city: "Atlanta", state: "GA", type: "Depot" },
  { id: "loc-service", name: "Service Center", city: "Columbus", state: "OH", type: "Service Center" },
  { id: "loc-dist", name: "Distribution Center", city: "Denver", state: "CO", type: "Distribution Center" },
  { id: "loc-west", name: "West Depot", city: "Phoenix", state: "AZ", type: "Depot" },
  { id: "loc-cross", name: "Crossdock Terminal", city: "Memphis", state: "TN", type: "Crossdock" },
];

export const CUSTOMERS = [
  "Summit Retail Group",
  "Northline Grocers",
  "Apex Hardware Co.",
  "Cascade Foods",
  "Union Freight Partners",
  "Brightpath Pharmacies",
  "Meridian Auto Parts",
  "Coastal Furniture Co.",
  "Vantage Electronics",
  "Harborview Textiles",
  "Golden State Produce",
  "Ironclad Industrial Supply",
  "Bluebird Logistics Retail",
  "Prairie Home Goods",
  "Redwood Building Materials",
  "Everline Beverages",
  "Falcon Sporting Goods",
  "Silverline Appliances",
  "Timberline Lumber Co.",
  "Crestview Wholesale",
];
